author: oToToT

keywords: CTF, Blog, oToToT

description: 紀錄oToToT的各種瑣事

# 导航栏头部名称
nav_name: oToToT

# 导航栏座右铭
motto: "存在與不存在，無論事物的想法"

github: "https://github.com/oToToT/"

# 站点图标和APP图标
favicon: 
  icon: /images/favicon.ico
  touch_icon: /images/touch-icon.png

# RSS文件位置
rss: 

# 自定义样式文件
custom_styles: 

# 自定义脚本文件
custom_scripts: 

# 代码高亮主题: normal | night | night blue | night bright | night eighties
highlight_theme: "night eighties"

# 开启数学公式渲染
mathjax: true

copyright:
  enable: false
  author: "董沅鑫"
  show_link: true
  more: '版权声明: 本博客所有文章除特别声明外, 均采用 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a> 许可协议. 转载请注明出处!'

# 建站时间. 格式：YYYY-MM-DD
start_time: "2019-06-15"

# 如何开启 评论&统计 插件：https://godbmw.com/passages/2018-11-15-theme-bmw-docs-zh/
# 请申请自己的 appid 和 appkey，并且替换下面的 appid 和 appkey
leancloud:
  appid: Hyq9wkH495DgNHWhDQCOfQSp-gzGzoHsz # 填写您的appid
  appkey: WaR7nrzhliHj9aVwdQzkdlGd # 填写您的appkey
  comment: false # 是否开启评论系统
  count: false # 是否开启文章统计

# 需要保证leancloud.count为true
welcome: 
  enable: false
  interval: 30

# 需要保证leancloud.comment为false
disqus: 
  enable: true
  id: "github-ototot"

# 需要保证leancloud.count为false
busuanzi: false

# 存放sha256加密的密码
# 拥有所有加锁文章的阅读权限
passwords: 
  - c967350c7e652c6305ef7c7dba4feb6b1106bba85fbef5d08d1897ef42fd5ffd

share:
  twitter: true
  facebook: true
  weibo: false
  qq: false
  wechat: false

analytics:
  baidu:
    enable: false
  google:
    enable: false
    id: 
  "360":
    enable: false
    id: 

# 打赏图片
#reward:
#  -
#    src: /images/wechat.png
#    alt: "WeChat"
#  -
#    src: /images/alipay.png
#    alt: "AliPay"

# 第三方库的CDN地址
# 请根据情况自行决定是否替换为国内CDN
cdn: 
  leancloud: "//cdn.jsdelivr.net/npm/leancloud-storage@3.11.1/dist/av-min.js"
  mathjax: "//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"
  valine: "//unpkg.com/valine/dist/Valine.min.js"
  busuanzi: "//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"
  font_awesome: "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"

nav:
  -
    name: "首頁"
    path: "/"
  -
    name: "文章列表"
    path: "/archives/"
  -
    name: "標籤"
    path: "/tags/"
  -
    name: "分類"
    path: "/categories/"
#  -
#    name: "友情連結"
#    path: "/friends/"
  -
    name: "關於"
    path: "/about/"

footer:
  -
    title: "更多關於我"
    children: 
      -
        name: "OI解題雜筆"
        path: "https://blog.ototot.tk"
      -
        name: "Codeforces"
        path: "https://codeforces.com/profile/oToToT"
      -
        name: "CTF Time"
        path: "https://ctftime.org/user/46758"

footer_contact: "Email: ty1208chiang@gmail.com"

friends_avatar_cdn: 
friends:
  -
    nickname: GodBMW
    avatar: /images/friends/godbmw.jpeg
    site: https://godbmw.com/
    meta: 主題作者
    show: true
